version: '3'

services:
  pollapp-backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - /home/pollapp/node_modules
      - .:/home/pollapp
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DATABASE=${PG_DATABASE}
      - PG_DATABASE_TEST=${PG_DATABASE_TEST}
      - PORT=${PORT}
      - CLIENT_ID=${CLIENT_ID}
      - NODE_ENV=development
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - database-network
      - redis-network
networks:
  database-network:
    external:
      name: ${DATABASE_NETWORK}
  redis-network:
    external:
      name: ${REDIS_NETWORK}
